# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()
a = np.array([1,2,3,4,5])

# Create a 2-dimensional NumPy array using np.array()
b = np.array([[1,2],[3,4]])

# Create a 3-dimensional Numpy array using np.array()
c = np.array([
    [[1,2], [3,4]],[[5,6],[7,8]]
])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [3]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a.shape, a.ndim, a.dtype, a.size, type(a)

((5,), 1, dtype('int64'), 5, numpy.ndarray)

In [4]:
# Attributes of 2-dimensional array
b.shape, b.ndim, b.dtype, b.size, type(b)

((2, 2), 2, dtype('int64'), 4, numpy.ndarray)

In [5]:
# Attributes of 3-dimensional array
c, c.shape, c.ndim, c.dtype, c.size, type(c)

(array([[[1, 2],
         [3, 4]],
 
        [[5, 6],
         [7, 8]]]),
 (2, 2, 2),
 3,
 dtype('int64'),
 8,
 numpy.ndarray)

In [6]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd 
df = pd.DataFrame(b)
df

0  1
0  1  2
1  3  4

In [7]:
# Create an array of shape (10, 2) with only ones
onesarray = np.ones((10,2))
onesarray

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [8]:
# Create an array of shape (7, 2, 3) of only zeros
onlyzeros = np.zeros((7,2,3))
onlyzeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [9]:
# Create an array within a range of 0 and 100 with step 3
arr = np.arange(0,100, 3)
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [10]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
randomarray = np.random.randint(0, 10, size=(7,2) )
randomarray

array([[9, 8],
       [5, 5],
       [1, 5],
       [9, 3],
       [2, 7],
       [3, 6],
       [1, 0]])

In [11]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
randomarray = np.random.rand(3,5)
randomarray

array([[0.4977077 , 0.15948917, 0.29892969, 0.87931096, 0.6758322 ],
       [0.03456709, 0.51539863, 0.65441718, 0.59568872, 0.51488467],
       [0.01656744, 0.44386403, 0.0997903 , 0.22555984, 0.0891043 ]])

In [12]:
# Set the random seed to 42
np.random.seed(0)

# Create a random array of numbers between 0 & 10 of size (4, 6)
randarr = np.random.randint(0,10, size=(4,6))
randarr

array([[5, 0, 3, 3, 7, 9],
       [3, 5, 2, 4, 7, 6],
       [8, 8, 1, 6, 7, 7],
       [8, 1, 5, 9, 8, 9]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [13]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
c = np.random.randint(1,10, size=(3,7))
print(c)
# Find the unique numbers in the array you just created
uniqueNumbers = np.unique(c)
print(uniqueNumbers)

[[5 4 1 4 6 1 3]
 [4 9 2 4 4 4 8]
 [1 2 1 5 8 4 3]]
[1 2 3 4 5 6 8 9]


In [14]:
# Find the 0'th index of the latest array you created
c[0]

array([5, 4, 1, 4, 6, 1, 3])

In [15]:
# Get the first 2 rows of latest array you created
c[:2,:]

array([[5, 4, 1, 4, 6, 1, 3],
       [4, 9, 2, 4, 4, 4, 8]])

In [16]:
# Get the first 2 values of the first 2 rows of the latest array
c[:2, :2]

array([[5, 4],
       [4, 9]])

In [17]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
randa = np.random.randint(0,10, size=(3,5))
onea = np.ones((3,5))
print(randa)
print(onea)

[[7 2 0 0 4]
 [5 5 6 8 4]
 [1 4 9 8 1]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [18]:
# Add the two arrays together
arrsum = randa + onea
print(arrsum)

[[ 8.  3.  1.  1.  5.]
 [ 6.  6.  7.  9.  5.]
 [ 2.  5. 10.  9.  2.]]


In [19]:
# Create another array of ones of shape (5, 3)
anotherone = np.ones((5,3))

In [20]:
# Try add the array of ones and the other most recent array together
arrsum2 = arrsum + anotherone.T
print(arrsum2)

[[ 9.  4.  2.  2.  6.]
 [ 7.  7.  8. 10.  6.]
 [ 3.  6. 11. 10.  3.]]


When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [21]:
# Create another array of ones of shape (3, 5)
antherone2 = np.ones((3,5))
antherone2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
# Subtract the new array of ones from the other most recent array
arr = arrsum2 - antherone2

In [23]:
print(arr)

[[ 8.  3.  1.  1.  5.]
 [ 6.  6.  7.  9.  5.]
 [ 2.  5. 10.  9.  2.]]


In [24]:
# Multiply the ones array with the latest array
arr * antherone2

array([[ 8.,  3.,  1.,  1.,  5.],
       [ 6.,  6.,  7.,  9.,  5.],
       [ 2.,  5., 10.,  9.,  2.]])

In [25]:
# Take the latest array to the power of 2 using '**'
arr ** 2

array([[ 64.,   9.,   1.,   1.,  25.],
       [ 36.,  36.,  49.,  81.,  25.],
       [  4.,  25., 100.,  81.,   4.]])

In [26]:
# Do the same thing with np.square()
np.square(arr)

array([[ 64.,   9.,   1.,   1.,  25.],
       [ 36.,  36.,  49.,  81.,  25.],
       [  4.,  25., 100.,  81.,   4.]])

In [27]:
# Find the mean of the latest array using np.mean()
np.mean(arr)

5.266666666666667

In [28]:
# Find the maximum of the latest array using np.max()
np.max(arr)

10.0

In [29]:
# Find the minimum of the latest array using np.min()
np.min(arr)

1.0

In [30]:
# Find the standard deviation of the latest array
np.std(arr)

2.885981442921782

In [31]:
# Find the variance of the latest array
np.var(arr)

8.32888888888889

In [32]:
# Reshape the latest array to (3, 5, 1)
arr2 = arr.reshape(3,5,1)

In [33]:
# Transpose the latest array
arr2.T

array([[[ 8.,  6.,  2.],
        [ 3.,  6.,  5.],
        [ 1.,  7., 10.],
        [ 1.,  9.,  9.],
        [ 5.,  5.,  2.]]])

What does the transpose do?

In [34]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
a = np.random.randint(0,10, size=(3,3))
b = np.random.randint(0,10, size=(3,2))
a,b

(array([[1, 7, 9],
        [9, 3, 6],
        [7, 2, 0]]),
 array([[3, 5],
        [9, 4],
        [4, 6]]))

In [35]:
# Perform a dot product on the two newest arrays you created
a @ b

array([[102,  87],
       [ 78,  93],
       [ 39,  43]])

In [36]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
c = np.random.randint(0,10, size=(4,3))
d = np.random.randint(0,10, size=(4,3))
c,d

(array([[4, 4, 3],
        [4, 4, 8],
        [4, 3, 7],
        [5, 5, 0]]),
 array([[1, 5, 9],
        [3, 0, 5],
        [0, 1, 2],
        [4, 2, 0]]))

In [38]:
# Perform a dot product on the two newest arrays you created
c @ d

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 3)

It doesn't work. How would you fix it?

In [39]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
c.T @ d

array([[36, 34, 64],
       [36, 33, 62],
       [27, 22, 81]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [40]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
a = np.random.randint(0,10, size=(2,2))
b = np.random.randint(0,10, size=(2,2))
a,b

(array([[3, 2],
        [0, 7]]),
 array([[5, 9],
        [0, 2]]))

In [41]:
# Compare the two arrays with '>'
a > b

array([[False, False],
       [False,  True]])

What happens when you compare the arrays with `>`?

In [42]:
# Compare the two arrays with '>='
a >= b

array([[False, False],
       [ True,  True]])

In [43]:
# Find which elements of the first array are greater than 7
listofelements = b[b>7]
listofelements

array([9])

In [44]:
# Which parts of each array are equal? (try using '==')
a == b

array([[False, False],
       [ True, False]])

In [45]:
# Sort one of the arrays you just created in ascending order
b.sort()
b

array([[5, 9],
       [0, 2]])

In [46]:
# Sort the indexes of one of the arrays you just created
sorted_indexes = b.argsort()
sorted_indexes

array([[0, 1],
       [0, 1]])

In [47]:
# Find the index with the maximum value in one of the arrays you've created
b.argmax()

1

In [48]:
# Find the index with the minimum value in one of the arrays you've created
b.argmin()

2

In [49]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
b.argmax(axis=1)

array([1, 1])

In [50]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created


In [51]:
# Create an array of normally distributed random numbers
np.random.randn(3,3)

array([[-0.01234481,  0.04212149,  1.95929589],
       [-0.1984257 ,  0.33053441, -1.43582841],
       [ 0.02752832,  1.12060466, -0.22403878]])

In [52]:
# Create an array with 10 evenly spaced numbers between 1 and 100
j = np.linspace(1,100,10)
j = j.reshape(2,5)
j

array([[  1.,  12.,  23.,  34.,  45.],
       [ 56.,  67.,  78.,  89., 100.]])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.

# Practical Numpy

<img src="images/numpy-pandas.j">

In [55]:
#Turn an image into a NumPy array
from matplotlib.image import imread
panda = imread("../images/numpy-pandas.jpeg")
print(type(panda))

FileNotFoundError: [Errno 2] No such file or directory: '../images/numpy-pandas.jpeg'

In [54]:
import os

current_directory = os.getcwd()
print("Current Working Directory:", current_directory)


Current Working Directory: /Users/jenilpadshala/Machine-Learning-Journey/ztm-ml/zero-to-mastery-ml-master/numpy
